### ISSUE TITLE
[DATASET] New dataset

### ISSUE THREAD

**Issue by jmachowinski** [vschroeter/rosmetasys-datasets#2]
[0122nodes_2024-08-06_11-15-18_singulate.zip](https://github.com/user-attachments/files/16508241/0122nodes_2024-08-06_11-15-18_singulate.zip)
Here is a new ROS2 meta system dataset generated with [rosmetasys](https://github.com/vschroeter/rosmetasys).

I agree to the following:
- By publishing the dataset in this issue, I consent to its storage in this open-source repository.
- By publishing the dataset in this issue, I consent to its usage for implementing and evaluating graph and visualization algorithms. 
- [x] I consent to the publication of the dataset under the CC BY-SA license (e.g., on [Zenodo}(https://zenodo.org/)).

Here are some details about the origin of the data:
- Simulation of a pacel singulation robot

Using this json, the visualization website freezes my firefox. 
@vschroeter please post a short message here, as soon as the visualization works with our data set.

**Comment by vschroeter** [comment]
Thanks a lot for the dataset!

I'll fix the problem with the freezing visualization, it shouldn't take long.

However, on a quick look, I saw that your dataset contains every node 2 times, one time for ROS_LOCALHOST_ONLY=1 and one time for =0. Is this an expected behavior of your system or a bug from the exporter?

**Comment by vschroeter** [comment]
@jmachowinski The freeze is fixed and online.
However, the prototype shows the shortcomings that we are currently working on in terms of scalability and usability for larger systems:
<img width="977" alt="image" src="https://github.com/user-attachments/assets/5f668ba2-ead1-4666-a8ef-d2c0ce2a77e4">

Especially the nodes that are connected to every other node in the system, such as the snapshotter or the node_orchastrator nodes in your case, lead to quite a mess in the current state. 

But we are working on solving that. Thanks again for the dataset!

**Comment by jmachowinski** [comment]
> However, on a quick look, I saw that your dataset contains every node 2 times, one time for ROS_LOCALHOST_ONLY=1 and one time for =0. Is this an expected behavior of your system or a bug from the exporter?

Our system **should** be ROS_LOCALHOST_ONLY. That being said, I am not sure, if we got a bug in our system configuration, or your exporter. Do you know a way of verifying this ?

Our DDS Configuration is :
```
ROS_DOMAIN_ID: 0
ROS_AUTOMATIC_DISCOVERY_RANGE: "LOCALHOST"
ROS_STATIC_PEERS: "127.0.0.1"
RMW_IMPLEMENTATION: "rmw_cyclonedds_cpp"
CYCLONEDDS_URI: |
  <General>
    <AllowMulticast>true</AllowMulticast>
    <Interfaces><NetworkInterface name="lo"/></Interfaces>
  </General>
  <Discovery>
    <ParticipantIndex>auto</ParticipantIndex>
    <MaxAutoParticipantIndex>1000</MaxAutoParticipantIndex>
  </Discovery>
```

**Comment by vschroeter** [comment]
I've just been experimenting a bit and found out, that the temporary node created in the exporter tool can sometimes discover nodes that it shouldn't be able to discover. 

From previous experiments, I thought that nodes started with ROS_LOCALHOST_ONLY=1 would only be able to discover other nodes also started with =1, and vice versa.
However, if the temporary exporter node is started with =1, it can discover all nodes, whether started with or without ROS_LOCALHOST_ONLY.
On the other hand, if the temporary exporter node is started with =1, it cannot detect any other nodes that were started with =0, but only nodes with =1.

I find this somewhat inconsistent, but I think this is fixed by the [Improved Dynamic Discovery](https://docs.ros.org/en/jazzy/Tutorials/Advanced/Improved-Dynamic-Discovery.html) in newer versions.

So I think your system is fine. 

I've updated the exporter tool to only include nodes once.
